### ISSUE TITLE
Posts can't be added or removed by https://my.eplay.com/broadcaster/edit/337169331994025984

### ISSUE THREAD

**Issue by VeljkoVasojevic** [dlxmedia/community#14]
### 🦄 Select your Profile

- [X] Streamer
- [ ] User

### ⚙️ Device

- [ ] Phone
- [X] Computer

### 💾 System

WINDOWS

### 🖥️ Browser

CHROME

### 📍 Where is the Bug?

📺 CHANNEL

### 🔗 Which page is it?

https://my.eplay.com/channel/post/statistics

### ℹ️ Description

Ecoticamaya can't edit her posts, add them, or remove them.

Tried going offline, disabling the Block Country option, and clearing the cache and cookies, but nothing worked.

![image_jmi8b7](https://user-images.githubusercontent.com/122928409/215768379-59a509f3-20fe-48aa-8c46-d8765de4b812.png)

### 🧨 How to reproduce

Tried going offline, disabling the Block Country option, and clearing the cache and cookies, but nothing worked.

![image_jmi8b7](https://user-images.githubusercontent.com/122928409/215768379-59a509f3-20fe-48aa-8c46-d8765de4b812.png)

### 😇 Anything else you could add?
it seems the error is related to missing performer param
<img width="1464" alt="Screenshot 2023-01-31 at 2 17 16 PM" src="https://user-images.githubusercontent.com/7253844/215771087-1a56257e-59a9-4559-8835-a119e1c981c6.png">

**Comment by ecilion** [comment]
I removed the performer (tagged user) from the DB, it seems to have fixed it
