### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by VeljkoEPLAY** [dlxmedia/community#15]
### 🦄 Select your Profile

- [ ] Streamer
- [X] User

### ⚙️ Device

- [ ] Phone
- [X] Computer

### 💾 System

OTHER

### 🖥️ Browser

OTHER

### 📍 Where is the Bug?

🛒 BUY TOKENS

### 🔗 Which page is it?

https://my.eplay.com/user/edit/413803396356243457

### ℹ️ Description

The customer bought 2 x 48$ and got 2 x $20 packages. Reported on Slack too. 

### 🧨 How to reproduce

1. I was on 
2. Then I clicked on
3. And then

**Comment by ecilion** [comment]
@VeljkoEPLAY closing this issue, it has been fixed, I guess.
