### ISSUE TITLE
:lady_beetle: Typing a letter in the chat moves the cursor to the end of the text

### ISSUE THREAD

**Issue by cuddlez42** [dlxmedia/community#67]
### 🦄 Select your Profile

- [ ] Streamer
- [X] User

### ⚙️ Device

- [ ] Phone
- [X] Computer

### 💾 System

WINDOWS

### 🖥️ Browser

FIREFOX

### 📍 Where is the Bug?

💬 LIVE CHATROOM

### 🔗 Which page is it?

https://www.eplay.com/ibivywilde/live

### ℹ️ Description

Every time a character is entered into the live chat, the cursor jumps to the end of the message. This makes it very difficult to edit messages before submitting them.

### 🧨 How to reproduce

1. In a live chatroom
2. Type a message e.g. "This is a test"
3. Try to change the middle of the message (for example, type the word "message" between "This" and "is")
4. After typing the first letter (e.g. "m") the cursor jumps to the end of the chat box

### ⚡️ Expected Behavior

The cursor for entering text should stay immediately after the last character typed

### 😇 Anything else you could add?

https://github.com/dlxmedia/community/assets/126299368/6aeb04e2-ff79-48e8-b093-14f3b1869c6b

**Comment by Korrieanne** [comment]
@cuddlez42 We wanted to let you know that we got your ticket, and our team is already working on it.

Please allow us up to 24 hours to conduct a thorough assessment and testing to understand the nature of your reported issue. We want you to know that our primary goal is to resolve your concern quickly.

Please don't worry, if it becomes necessary to escalate your ticket to our Tier 2 support team, we will immediately notify you with all the details. We want you to know that your satisfaction is important to us, and we are committed to providing you with the best possible assistance.

**Comment by gregoriSCTR** [comment]
I managed to replicate it both PC and Mobile. It's also happening when you delete any written character.

I tried on Dev too  => https://www-development.eplay.com/

https://github.com/dlxmedia/community/assets/122129031/d511a474-97dd-43dd-b79f-022b01faebd4

**Comment by Korrieanne** [comment]
@xansing We tested and verified!
